[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'npm cache clean --force',
  'rm -rf node_modules package-lock.json',
  'npm install --production --no-package-lock'
]

[start]
cmd = 'npm start' 